using System.Collections;
using System.Collections.Generic;
using UnityEngine;

// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var JsonHelper = JsonHelper.FromJson(jsonString);
// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
// Root myDeserializedClass = JsonConvert.DeserializeObject<Root>(myJsonResponse);
public class Root
{
    public Tr tr { get; set; }
    public En en { get; set; }
}

public class En
{
    public SingleEnemy singleEnemy { get; set; }
    public Player player { get; set; }
    public MutlipleEnemies mutlipleEnemies { get; set; }
    public All all { get; set; }
}

public class Tr
{
    public SingleEnemy singleEnemy { get; set; }
    public Player player { get; set; }
    public MutlipleEnemies mutlipleEnemies { get; set; }
    public All all { get; set; }
}

public class All
{
}

public class MutlipleEnemies
{
    public Lightning lightning { get; set; }
}

public class Player
{
    public Guard guard { get; set; }
}

public class SingleEnemy
{
    public Attack attack { get; set; }
    public Slay slay { get; set; }
}

public class Attack
{
    public string name { get; set; }
    public string description { get; set; }
    public int damage { get; set; }
    public string types { get; set; }
}

public class Guard
{
    public string name { get; set; }
    public string description { get; set; }
    public int shield { get; set; }
    public string types { get; set; }
}

public class Lightning
{
    public string name { get; set; }
    public string description { get; set; }
    public int damage { get; set; }
    public string types { get; set; }
}

public class Slay
{
    public string name { get; set; }
    public string description { get; set; }
    public int damage { get; set; }
    public string types { get; set; }
}